In [6]:
import tensorflow as tf

In [20]:
ten1 = tf.constant([1,2,3])
ten2 = tf.constant([4,5,6])
ten3 = tf.constant([[1,2],
                    [3,4],
                    [5,6]])
w = tf.Variable(1.0)  # weight / 변수


In [17]:
print(ten1+ten2)
print(ten3)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [18]:
print(tf.add(ten1,ten2))

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [22]:
tf.zeros(10)
# tf.shape()    
# tf.cast()
print(w)
#w.numpy()
w.assign(2)
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.0>


In [40]:
키 = 170
신발 = 260
#신발 = 키 * a + b 

a = tf.Variable(0.1)
b = tf.Variable(0.2)

def 손실함수():
    예측값 = 키 * a + b
    return tf.square( 260 - 예측값 )

opt = tf.keras.optimizers.Adam(learning_rate=0.1)

for i in range (0,10000):
    opt.minimize(손실함수, var_list = [a,b])




tf.Tensor(260.0, shape=(), dtype=float32)


In [43]:
print(a.numpy(),b.numpy())

1.5198832 1.6198834


In [44]:
키 = 180
print(키*a + b)

tf.Tensor(275.19885, shape=(), dtype=float32)
